### PR TITLE
Handle large request results

### PR DESCRIPTION
**Pull request by sschuberth**
This transparently handles pagination if requests are larger than the internal / specified result limit.

### CODE REVIEW

**Comment by trumant** [comment]
@sschuberth Thank you for your contribution. Supporting paginated results from the Gerrit API is definitely a great enhancement.

It looks like this change has broken some existing specs and I don't see any new specs or fixtures for the paginated responses. Can you take a look at the spec failures please?

**Comment by sschuberth** [comment]
@trumant I've fixed the test failure. Will look into adding more tests soonish.

**Comment by sschuberth** [comment]
@trumant While developing the test I actually found a bug. I'll rebase my work on top of master and open a new PR incl. tests.

**Comment by trumant** [comment]
Thanks for developing the test @sschuberth

Looking forward to seeing the next PR

**Comment by sschuberth** [comment]
@trumant Please see PR #10 :-)

**Pull request merged**
